### ISSUE TITLE
Safety: Cannot unify safetybugs.TypedHolder<Null<String>> with safetybugs.TypedHolder<String>

### ISSUE THREAD

**Issue by restorer** [RealyUniqueName/Safety#14]
```haxe
class TypedHolder<T> {
    public var v : T;

    public function new(v : T) {
        this.v = v;
    }
}

class Bug9 {
    public function bug() : Void {
        var s : Null<String> = ((Math.random() > 0.5) ? "A" : null);

        if (s != null) {
            // Safety: Cannot unify safetybugs.TypedHolder<Null<String>> with safetybugs.TypedHolder<String>
            var h : TypedHolder<String> = new TypedHolder(s);
        }
    }
}
```

See https://github.com/restorer/haxe-safety-bugs/blob/master/safetybugs/Main.hx#L128 for working example.

**Comment by restorer** [comment]
This is for Haxe 4.0.0-preview.5 and Safety from master.

**Comment by RealyUniqueName** [comment]
Unfortunately, this is not avoidable in the plugin, because Safety cannot modify the typing process. 
Use `new TypeHolder((s:String))` as a workaround.

**Comment by restorer** [comment]
Currently I use `.unsafe()`, it looks better for me. Probably this should be mentioned in documentation somewhere.

**Comment by RealyUniqueName** [comment]
`.unsafe()` is not safe :)
If you ever remove or change `if(s != null)`, your code will become unsafe. While with `(s:String)` it will emit a compilation error.

**Comment by RealyUniqueName** [comment]
Another option is `new TypeHolder<String>(s)`.
